In [39]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=10000, n_features=4, n_informative=2, n_redundant=0,random_state=0, shuffle=False)


In [11]:
X

array([[-0.85255585,  1.00312536,  0.53286612,  0.76440094],
       [-0.16171265,  1.55666395, -0.85608336, -1.6823405 ],
       [-1.36883328,  0.11776563,  0.65306946,  0.93025508],
       ...,
       [ 1.46718799,  1.63720032,  1.23934523,  0.3642774 ],
       [ 1.07113253,  1.15113659, -1.16663743, -0.50382808],
       [ 1.63564375,  2.24896687,  0.11141039, -1.53470286]])

In [12]:
X.shape

(10000, 4)

In [13]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [14]:
y.shape

(10000,)

In [16]:
clf = BaggingClassifier(estimator=SVC(),n_estimators=10, random_state=0).fit(X, y) ## n_estimators means number of model we have traning


In [17]:
clf.predict([[0, 0, 0, 0]])

array([0])

In [18]:
clf.score(X,y)

0.8831

In [19]:
clf = BaggingClassifier(estimator=SVC(),n_estimators=50, random_state=0).fit(X, y) ## n_estimators means number of model we have traning


In [20]:
clf.score(X,y)

0.882

In [21]:
clf.predict([[-0.85255585,  1.00312536,  0.53286612,  0.76440094]])

array([1])

In [22]:
clf.predict([[ 1.63564375,  2.24896687,  0.11141039, -1.53470286]])

array([1])

In [23]:
from sklearn.ensemble import RandomForestClassifier

In [29]:
clf2 = RandomForestClassifier(n_estimators=50,max_depth=8, random_state=0)
clf2.fit(X, y)

RandomForestClassifier(max_depth=8, n_estimators=50, random_state=0)

In [30]:
clf2.score(X,y)

0.922

In [31]:
## max_depth [8 to 32]

In [32]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier, VotingClassifier


In [42]:
clf1 = LogisticRegression(random_state=1)
clf2 = RandomForestClassifier(n_estimators=50, random_state=1)
clf3 = SVC()


In [43]:
eclf1 = VotingClassifier(estimators=[
        ('lr', clf1), ('rf', clf2), ('gnb', clf3)], voting='hard')

In [44]:
eclf1 = eclf1.fit(X, y)

In [45]:
eclf1.score(X,y)

0.8895

In [50]:
from sklearn.ensemble import StackingClassifier
from sklearn.svm import LinearSVC

In [52]:

estimators = [
    ('rf', RandomForestClassifier(n_estimators=10, random_state=42)),
    ('svr',LinearSVC(random_state=42))
                          
]
clf = StackingClassifier(
    estimators=estimators, final_estimator=LogisticRegression()
)

In [53]:
clf.fit(X,y)

StackingClassifier(estimators=[('rf',
                                RandomForestClassifier(n_estimators=10,
                                                       random_state=42)),
                               ('svr', LinearSVC(random_state=42))],
                   final_estimator=LogisticRegression())

In [55]:
clf.score(X,y)

0.9899