## stats 

In [3]:
import pandas as pd

In [4]:
data=[12,24,32,45,12,43,67,45,32,52,32]

In [7]:
data2=pd.read_csv("https://raw.githubusercontent.com/sunnysavita10/Statistics-With-Python-CompleteGuide/refs/heads/main/Iris.csv")

In [8]:
data2

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [9]:
data3=pd.read_csv("https://raw.githubusercontent.com/sunnysavita10/Statistics-With-Python-CompleteGuide/refs/heads/main/Titanic.csv")

In [10]:
data3

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
scipy
statsmodel
statistics
pandas 
numpy
malplotlib
seaborn
plotly


In [11]:
data

[12, 24, 32, 45, 12, 43, 67, 45, 32, 52, 32]

In [13]:
data.sort()

In [14]:
data


[12, 12, 24, 32, 32, 32, 43, 45, 45, 52, 67]

In [15]:
data_copy=data.copy()

In [ ]:
mean
median
mode

In [16]:
import numpy as np

In [19]:
y=len(data)

In [20]:
y

11

In [33]:
data

[12, 12, 24, 32, 32, 32, 43, 45, 45, 52, 67]

In [34]:
round(np.mean(data),3)

36.0

In [35]:

y=len(data)
x=0
for i in data:
    
    x=(x+i)
    
z=x/y
print(z)

36.0


In [36]:
sum(data)

396

In [37]:
## median of the data 


In [38]:
np.median(data)

32.0

In [39]:
# mode of the data

In [43]:
np.mode(data) ## no module in numpy mode

AttributeError: module 'numpy' has no attribute 'mode'

from 

In [41]:
from statistics import mode

In [42]:
mode(data)

32

In [44]:
data

[12, 12, 24, 32, 32, 32, 43, 45, 45, 52, 67]

In [45]:
data=[12, 12, 24, 32, 32, 32, 43, 45, 45, 52, 67,200,1000]

In [48]:
# if we have a outlier in my data so i wan't use mean
np.mean(data)

122.76923076923077

In [49]:
np.median(data)

43.0

## dispersion of the data
## 1. percentile of the data
## 2. std dev
## 3. variance 

In [51]:
np.percentile(data_copy,[25,50])

array([28., 32.])

In [52]:
np.percentile(data_copy,[25,50,75])

array([28., 32., 45.])

In [53]:
np.percentile(data_copy,[25,50,75,100])

array([28., 32., 45., 67.])

In [54]:
# IQR=q3-q1

In [55]:
45-28

17

## upper_bound=(IQR+1.5*q3)
## lower_bound=(IQR-1.5*q1)